# action.yml
name: "QCVE - Code Scanning"
description: "Run CodeQL Query against Public Project Databases"

inputs:
  username:
    description: 'Username'
    required: true
  report:
    description: 'Report path'
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - USERNAME=${{ inputs.username }}